### PR TITLE
Support Sentry's performance monitoring feature

### PR DESCRIPTION
**Pull request by ohana54**
This PR adds support for [Sentry's performance monitoring feature](https://sentry.io/for/performance).\
Support was added for all interception kinds, and docs were updated as well.

### CODE REVIEW

**Review by zivl — COMMENTED** [review]
i'll be happy for a zoom call so we can talk through the PR and the general topic

**Review by zivl — APPROVED** [review]
I've started using transactions as well!
Really thanks for this PR, now I understand how urge i should have addressed that open issue before...

**Comment by zivl** [comment]
oh sorry, i forgot... handling right now

**Comment by zivl** [comment]
done - release in `sentry-testkit@3.3.3`

**Comment by ohana54** [comment]
Awesome, thanks!!

**Pull request merged**
