### PR TITLE
feat: migrate to TypeScript

### PR DESCRIPTION
**Pull request by sidoruk-sv**

### CODE REVIEW

**Comment by zivl** [comment]
Thanks @sidoruk-sv I was just speaking with @ohana54 about it!
so what's with the build's statuses?

**Comment by zivl** [comment]
oh just saw its a `draft`.
are you still working on it?

**Comment by sidoruk-sv** [comment]
@zivl yep, the only problem for now is `jest-mock.test.ts` file)
Could you please help me debug the problem there?

**Comment by zivl** [comment]
sending you a video call invitation

**Comment by zivl** [comment]
closed in favor of #137

**Pull request closed without merging**
